# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: all.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tall.proto\x12\x0fgoogle.protobuf\"<\n\x08\x63s_login\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\x04\"\x1b\n\x08sc_login\x12\x0f\n\x07\x65rrcode\x18\x01 \x01(\r\"\n\n\x08\x63s_heart\"\x1d\n\x08sc_heart\x12\x11\n\ttimestamp\x18\x01 \x01(\r\"\x0e\n\x0c\x63s_base_info\"\x1e\n\x0csc_base_info\x12\x0e\n\x06roleID\x18\x01 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'all_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CS_LOGIN._serialized_start=30
  _CS_LOGIN._serialized_end=90
  _SC_LOGIN._serialized_start=92
  _SC_LOGIN._serialized_end=119
  _CS_HEART._serialized_start=121
  _CS_HEART._serialized_end=131
  _SC_HEART._serialized_start=133
  _SC_HEART._serialized_end=162
  _CS_BASE_INFO._serialized_start=164
  _CS_BASE_INFO._serialized_end=178
  _SC_BASE_INFO._serialized_start=180
  _SC_BASE_INFO._serialized_end=210
# @@protoc_insertion_point(module_scope)
