%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.5

-ifndef(all).
-define(all, true).

-define(all_gpb_version, "4.19.5").

-ifndef('CS_LOGIN_PB_H').
-define('CS_LOGIN_PB_H', true).
-record(cs_login,
        {username = []          :: unicode:chardata() | undefined, % = 1, optional
         password = []          :: unicode:chardata() | undefined, % = 2, optional
         uuid = 0               :: non_neg_integer() | undefined % = 3, optional, 64 bits
        }).
-endif.

-ifndef('SC_LOGIN_PB_H').
-define('SC_LOGIN_PB_H', true).
-record(sc_login,
        {errcode = 0            :: non_neg_integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('CS_HEART_PB_H').
-define('CS_HEART_PB_H', true).
-record(cs_heart,
        {
        }).
-endif.

-ifndef('SC_HEART_PB_H').
-define('SC_HEART_PB_H', true).
-record(sc_heart,
        {timestamp = 0          :: non_neg_integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('CS_BASE_INFO_PB_H').
-define('CS_BASE_INFO_PB_H', true).
-record(cs_base_info,
        {
        }).
-endif.

-ifndef('SC_BASE_INFO_PB_H').
-define('SC_BASE_INFO_PB_H', true).
-record(sc_base_info,
        {roleID = 0             :: integer() | undefined % = 1, optional, 64 bits
        }).
-endif.

-endif.
